# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dozo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndozo.proto\x12\x03\x64zo\"?\n\rGameParameter\x12\x14\n\x0c\x62oard_length\x18\x01 \x01(\r\x12\x18\n\x10number_of_colors\x18\x02 \x01(\r\"/\n\x08GameTurn\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\r\n\x05\x63olor\x18\x03 \x01(\r\"i\n\tGameState\x12\x14\n\x0c\x62oard_length\x18\x01 \x01(\r\x12\x18\n\x10number_of_colors\x18\x02 \x01(\r\x12\x12\n\nboard_data\x18\x03 \x01(\x0c\x12\x18\n\x10remaining_stones\x18\x04 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dozo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GAMEPARAMETER']._serialized_start=19
  _globals['_GAMEPARAMETER']._serialized_end=82
  _globals['_GAMETURN']._serialized_start=84
  _globals['_GAMETURN']._serialized_end=131
  _globals['_GAMESTATE']._serialized_start=133
  _globals['_GAMESTATE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
