# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nim.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnim.proto\x12\x03nim\"D\n\rGameParameter\x12\x19\n\x11number_of_columns\x18\x01 \x01(\r\x12\x18\n\x10number_of_stones\x18\x02 \x01(\r\"9\n\x08GameTurn\x12\x15\n\rtarget_column\x18\x01 \x01(\r\x12\x16\n\x0enumber_to_take\x18\x02 \x01(\r\"\x1c\n\tGameState\x12\x0f\n\x07\x63olumns\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nim_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GAMEPARAMETER']._serialized_start=18
  _globals['_GAMEPARAMETER']._serialized_end=86
  _globals['_GAMETURN']._serialized_start=88
  _globals['_GAMETURN']._serialized_end=145
  _globals['_GAMESTATE']._serialized_start=147
  _globals['_GAMESTATE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
