# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tko.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttko.proto\x12\x03tko\"\x0f\n\rGameParameter\":\n\x08GameTurn\x12\n\n\x02x1\x18\x01 \x01(\r\x12\n\n\x02y1\x18\x02 \x01(\r\x12\n\n\x02x2\x18\x03 \x01(\r\x12\n\n\x02y2\x18\x04 \x01(\r\"\x1a\n\tGameState\x12\r\n\x05\x62oard\x18\x01 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tko_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GAMEPARAMETER']._serialized_start=18
  _globals['_GAMEPARAMETER']._serialized_end=33
  _globals['_GAMETURN']._serialized_start=35
  _globals['_GAMETURN']._serialized_end=93
  _globals['_GAMESTATE']._serialized_start=95
  _globals['_GAMESTATE']._serialized_end=121
# @@protoc_insertion_point(module_scope)
